### ISSUE TITLE
Simplify challenge provider selection

### ISSUE THREAD

**Issue by rndmh3ro** [T-Systems-MMS/ansible-collection-acme#42]
Right now we have to choose if we use a dns provider or http provider and then additionally choose which provider should be used. This seems redundant.

We could simplify this by only using one variable and infer from that what provider should be used, e.g.

`challenge_provider: dns_autodns`
`challenge_provider: http_local`

If the names between dns and http providers do not overlap, we could even omit the `dns_` or `http_` part, though keeping it for readability is probably a good idea, too.

What do you think?

**Comment by avalor1** [comment]
Seems like a realy good optimization to me. As you already mentioned, i would also keep the distinction between the providers for readabilty. Also this adds some kind of awareness for the used provider.

**Comment by schurzi** [comment]
&lt;irony&gt;
I think we could autochoose the provider by examining the auth/login settings in the variables
&lt;/irony&gt;

That being said, simplification is a good goal. I think we could omit the provider type from the variables. Because it will be clear from reading the documentation. DNS or HTTP (or X) is an implementation detail, that comes with the choice of the provider and can not be changed by the user. 

Naming providers might be an issue in the future, but I think if we use product names instead of platform names for our providers, this should work out. Currently that is honored on AWS, since we named the provider "s3", in Azure however we might need to change the name. Only "azure" is ambigous in this case. (same for Hetzner and OpenStack)

**Comment by rndmh3ro** [comment]
I just checked what other tools do in this case:
Certbot uses options that are named like `--dns-google`. (https://certbot-dns-google.readthedocs.io/en/stable/)
acme.sh uses options named like `--dns dns_azure` (https://github.com/acmesh-official/acme.sh/wiki/dnsapi).

> Naming providers might be an issue in the future, but I think if we use product names instead of platform names for our providers, this should work out. 

Renaming them would be a breaking change. Do we want to release a 2.0.0? I'm not sure.

To not make a breaking change we could stay with the current provider names and just ignore the `letsencrypt_do_http_challenge` and `letsencrypt_do_dns_challenge` variables.

**Comment by schurzi** [comment]
If we want to include the provider type in their name, this would also be a breaking change.

So I think youare right. just keeping the current names and ignoring te provider type would be the best way. if we discover further down, that we need a more complicated layout, we can always decide to do a breaking change and release a 2.0.0.

**Comment by avalor1** [comment]
Ah, good catch... didn't took this into account. For my part i dont want to release a 2.0 after this short time and also another breaking change. As you both suggested we should stick with the current names for now and wait at least some time before we release another breaking version.
I will look into this.

**Comment by avalor1** [comment]
Hm.... so we want to use the existing variables `letsencrypt_http_provider` `letsencrypt_dns_provider`? Using a new variable like `challenge_provider` would render the two mentioned vars useless and would also be a breaking change.

Also, if we would merge the provider "selection" into one list we would need some kind of list to compare and distinct between http and dns challenges tho chose the correct path/file. Something like that:
```
http_provider:
  - local
  - s3
dns_provider:
  - autodns
  - azure
  - hetzner
  - openstack
  - pebble
```
And then check if the chosen challenge_provider is in the correct/coresponding list:
```
- name: do http challenge
  include_tasks: http-challenge.yml
  when:
    - challenge_provider in http_provider

- name: do dns challenge
  include_tasks: dns-challenge.yml
  when:
    - challenge_provider in dns_provider
```
To finaly choose the correct path in our folder structure
```
- name: "do HTTP challenge with provider {{ challenge_provider }}"
  include_tasks: "{{ item }}"
  with_first_found:
    - "http-challenge/{{ challenge_provider }}.yml"
    - challenge-unknown.yml
```

I see one problem here: The lists of providers need to be updated when new providers are added, removed or renamed.
Thats not what we want, i think. 
In keeping the above mentionend variables we would be flexible when the providers are changed and also existing configurations will work as they are.

The suggested affix for the provider names would open up other posibilities of implementing but as we already discussed this would be a breaking change

**Comment by schurzi** [comment]
> Also, if we would merge the provider "selection" into one list we would need some kind of list to compare and distinct between http and dns challenges to chose the correct path/file. Something like that:

If we only use unique names in these two lists, there is no need to compare.

Executing the right provider seems easy.
```yaml
- name: "do challenge with provider {{ challenge_provider }}"
  include_tasks: "{{ item }}"
  with_first_found:
    - "dns-challenge/{{ challenge_provider }}.yml"
    - "http-challenge/{{ challenge_provider }}.yml"
    - challenge-unknown.yml
```

The other seteps you mentioned might be neccessary, when we want to check for strict adherence to variable definiion and maybe support additional errorchecking, but I think simply failing with "provider unknown" is da acceptable solution and it simplifies the code even more.

**Comment by avalor1** [comment]
Okay, that should work. Now there is only the change of the variables. Existing configurations will have to change the variables in their config: `letsencrypt_http_provider` `letsencrypt_dns_provider` > `challenge_provider` do we not consider this breaking?

**Comment by avalor1** [comment]
Hrm, just saw that this would skip the CSR and challenge creation which is separated into dns and http challenge files which get executed first. After this the provider files get called. 
`playbook.yml > main.yml > (http-challenge|dns-challenge).yml > provider.yml`

So we would need some kind of fact to hold the path of the provider to determine the challenge type from this. Or we could somehow merge both files into one. But i do not have a "fancy" solution to that right now.

Or we could include the dns- and http challenge files into the provider files. That would than be some kind of distinction and it would enable us to use the approach from @schurzi. On the other side this would be some kind of duplicate as this has to be present in every provider file.

**Comment by schurzi** [comment]
I think we should unify the CSR generation and split this our from the challenge. This has currently two problems to be solved:

* we have different ways of generation the CSR for normal and wildcard domains, wildcard domains currently only work with DNS Challenges (from my information)
maybe we could "solve" this by not checking and just passing the corresponding let's encrypt error when this happens, after all the users have to decide what they want to do and I think the error from the source is already verbose enough
* The challenge Type seems to be encoded in the task (`http-01`vs. `dns-01`)
this seems a bit more complex. The code seems to do some different thing depending on this setting. maybe the easiest thing we could do is, take the above task to select the challenge provider, write the provider file path in a variable before we generate the CSR and then set this variable according to the path of the provider. After this we include the provider from the path in the variable.

something like this pseudo playbook: (if we name the paths like the challenge provider types this getts easier)
```yaml
- name: "select provider {{ challenge_provider }}"
  set_fact:
    provider_path: "{{ item }}"
  with_first_found:
    - "challenge/dns-01/{{ challenge_provider }}.yml"
    - "challenge/http-01/{{ challenge_provider }}.yml"
    - challenge-unknown.yml

- name: "Create a challenge for..."
  acme_certificate:
...
    # e.g. path is "challenge/http-01/s3.yml" > dirname is "challenge/http-01" > last is "http-01"
    challenge: "{{ provider_path | dirname | last }}"
...

- name: "do challenge with provider {{ challenge_provider }}"
  include_tasks: "{{ provider_path }}"
```
